### PR TITLE
Fix large imports.

### PR DESCRIPTION
**Pull request by jim-barber-he**
**Description of the change**

This change fixes the issue described here:
https://github.com/bitnami/bitnami-docker-postgresql/issues/312

When working with large database dumps, trying to read the entire dump
into the sql_cmd shell variable hangs or takes so long as to appear to.

Removing the steps to read the dump into a variable and show it in debug
output, and to just let psql process stdin fixes things.

**Benefits**

This will allow large database dumps to be used to initialise the database.

**Possible drawbacks**

No debug output for the SQL being run.
But that is also a positive too.
I don't want my 1.2GiB dump being output to the terminal.

**Applicable issues**

https://github.com/bitnami/bitnami-docker-postgresql/issues/312

**Additional information**

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR! Could you let us know how the call to the function would look like now?

**Comment by jim-barber-he** [comment]
Hi.

There is no change; the function is called the same as it was before the change.
The psql command will process the query from stdin just like it did before.

**Review by juan131 — APPROVED** [review]
LGTM!! 

It'd be nice to have a way to preserve the "debug" message but IMHO if it's problematic and it's preventing the logic to work properly with large imports it's better to remove it.

**Comment by juan131** [comment]
Your changes were approved and merged @jim-barber-he 

New container images (one per supported branch) will be released including your changes during the next hours.

**Pull request merged**
