### PR TITLE
Always alter user if env is present

### LINKED ISSUE #193: Postgres pod has issues setting postgres_user and password
Team,

I am pulling bitnami/postgresql:12.1.0 for postgres image and passing below details as env variables as part of my deployment yaml. 

```
env:
          - name: POSTGRES_DB
            value: "db"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "pg@111"  
```

But still getting below error in the logs after kubernetes pod is up and running.

```
2020-02-03 10:56:21.457 GMT [1] LOG:  database system is ready to accept connections
2020-02-03 10:56:46.389 GMT [212] ERROR:  relation "Licenses" does not exist at character 15
--
  | 2020-02-03 10:56:46.389 GMT [212] STATEMENT:  SELECT * FROM "Licenses" WHERE expired = false AND expiration_date > now() LIMIT 1
  | 2020-02-03 10:57:06.303 GMT [213] FATAL:  password authentication failed for user "postgres"
  | 2020-02-03 10:57:06.303 GMT [213] DETAIL:  Password does not match for user "postgres".
```

Please assist.

### PR DESCRIPTION
**Pull request by nesies**
Fixes #193 

Always alter postgres pasword if POSTGRESQL_USERNAME is present
Always rename postgres user when POSTGRESQL_USERNAME is present

### CODE REVIEW

**Comment by andresbono** [comment]
Hi @nesies, thanks so much for submitting the PR! We will review it shortly.

**Comment by andresbono** [comment]
Hi @nesies, I'm afraid that we cannot merge this PR. How did you test it? We couldn't run the [docker-compose-replication.yml](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/docker-compose-replication.yml), the slave node crashes when trying to update the credentials. Even if we run a standalone container, it doesn't work if we recreate the container keeping the volumes.

**Comment by nesies** [comment]
thanks, i will check/test more cases

**Comment by andresbono** [comment]
Thanks, @nesies!! To be honest, on our side, we didn't find a clean solution to this issue yet.

**Pull request closed without merging**
