### PR TITLE
Restore POSTGRESQL_PASSWORD_FILE environment variables

### PR DESCRIPTION
**Pull request by dustinmm80**
**Description of the change**

This change restores fallbacks for two password environment variables that was removed in https://github.com/bitnami/bitnami-docker-postgresql/commit/543bbe34f9047f0524d8e32c7debf8e067ad8bdc#diff-e52440646458a3be1a6fcac9cc39e2cf. 

Right now the mistmatch between `POSTGRES_PASSWORD_FILE` (passed in via the `bitnami/postgresql` Helm chart) and `POSTGRESQL_PASSWORD_FILE` (expected by this image) causes the `postgresql` pod running the image to fail because no password is set.

**Benefits**

This allows the downstream `bitnami/postgresql` Helm chart users to use the `usePasswordFile` variable to store passwords as Kubernetes secrets that are then mounted as files into the `postgresql` pods.

**Possible drawbacks**

None that I can see.

**Applicable issues**

This should address these issues:
- https://github.com/bitnami/bitnami-docker-postgresql/issues/234
-  https://github.com/bitnami/charts/issues/3331

**Additional information**

### CODE REVIEW

**Comment by dustinmm80** [comment]
@dani8art can you take a look at this? I think this will fix https://github.com/bitnami/bitnami-docker-postgresql/issues/234.

**Comment by marcosbc** [comment]
Hi @dustinmm80, thanks for the contribution! I don't think this would fix the main issue, since the logic for importing the contents of the file to the envvar is located at lines 64-71 of the same file.

In any case, we understand this is an issue and are working on implementing a fix, expecting to have a container published tomorrow (unless anything unexpected comes), with the proper changes. We'll keep you posted!

P.S.: We expect the resulting file to look like this: https://gist.github.com/marcosbc/5da8182f2707a45f28f1756bf24d4188 If you want, you could update the PR with those changes, so when the container is released, the Git history links to these issues/PRs.

**Comment by dustinmm80** [comment]
Thanks for checking this out @marcosbc.

In the case of `POSTGRESQL_PASSWORD_FILE` and `POSTGRESQL_POSTGRES_PASSWORD_FILE`, I didn't think the loop on lines 64-71 applied since we want the values of these environment variables to be the paths to the files instead of the values of the files, since they are being mounted from k8s secrets. Reading from the secret on disk into an environment variable broadens the exposure of the secret, a security issue. Am I understanding this correctly?

**Comment by marcosbc** [comment]
@dustinmm80 Actually, those environment variables are paths to the files.

I.e. if `POSTGRESQL_PASSWORD_FILE` is set, the logic would try to set `POSTGRESQL_PASSWORD` to the contents of the path to the file specified in `POSTGRESQL_PASSWORD_FILE`.

So if `POSTGRESQL_PASSWORD_FILE` is set to `/tmp/mypassword`, `POSTGRESQL_PASSWORD` will be set to the contents of the `/tmp/mypassword` file.

**Comment by dustinmm80** [comment]
Ah okay, thanks for the explanation, I understand now. Much appreciated!

**Comment by marcosbc** [comment]
FYI this should be fixed in `10.13.0-debian-10-r77`, `11.8.0-debian-10-r79` and `12.3.0-debian-10-r79`, so I'm proceeding to close this.

**Comment by cdmikechen** [comment]
@marcosbc Sorry I can't find `12.3.0-debian-10-r79` in https://hub.docker.com/r/bitnami/postgresql/tags?page=1&name=12.3, is it published?

**Comment by marcosbc** [comment]
Hi @cdmikechen, it looks like there was an issue in our internal pipeline and it did not get released before 12.4.0 was available. Please refer to `12.4.0-debian-10-r0` instead.

**Pull request closed without merging**
